version: "3"

services:
  app:
    image: php:7.2-alpine
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8000}:8000"
    working_dir: /app
    command: [ "bin/console", "server:run", "0.0.0.0" ]

  encore:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: [ "yarn", "dev-server", "--host=0.0.0.0" ]
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: verybadpassword
    ports:
      - "3307:3307"
  pma: 
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8001:80"
